"""
dnsmark built-in exporter: Markdown
=====================================
Exports benchmark results as a Markdown table with a metadata section.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any, Optional

from dnsmark.plugin_base import ExporterPlugin, ServerStats

PLUGIN_INFO = {
    "name":        "Markdown Exporter",
    "version":     "1.0.0",
    "api_version": "1.0",
    "author":      "DNSMark contributors",
    "description": "Export results as a Markdown table",
    "type":        "exporter",
    "format":      "markdown",
    "requires":    [],
    "tags":        ["builtin"],
}


def _bool_str(v: Optional[bool]) -> str:
    if v is None:
        return "?"
    return "✓" if v else "✗"


def _fmt(v: Optional[float], ndigits: int = 1) -> str:
    if v is None:
        return "—"
    return f"{v:.{ndigits}f}"


def _pct(v: float) -> str:
    return f"{v * 100:.1f}%"


class MarkdownExporter(ExporterPlugin):
    """Export benchmark results to a Markdown table."""

    format         = "markdown"
    file_extension = ".md"

    def export(
        self,
        results:  list[ServerStats],
        filepath: str,
        *,
        lang:  str = "en",
        meta:  Optional[dict[str, Any]] = None,
    ) -> bool:
        """Write *results* to *filepath* as Markdown."""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        content = self._render(results, meta)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True

    def preview(
        self,
        results:  list[ServerStats],
        max_rows: int = 10,
        lang:     str = "en",
    ) -> str:
        return self._render(results[:max_rows], None)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _render(
        self,
        results:  list[ServerStats],
        meta:     Optional[dict[str, Any]],
    ) -> str:
        lines: list[str] = []

        # Title / header
        lines.append("# DNSMark Benchmark Results")
        lines.append("")

        # Metadata section
        lines.append("## Metadata")
        lines.append("")
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        lines.append(f"- **Generated:** {ts}")
        lines.append(f"- **Servers tested:** {len(results)}")
        if meta:
            for k, v in meta.items():
                lines.append(f"- **{k}:** {v}")
        lines.append("")

        # Results table
        lines.append("## Results")
        lines.append("")

        # Header row
        headers = [
            "Rank", "Server", "Score", "Avg ms", "Median", "P95",
            "Min", "Max", "Jitter", "Reliability", "DNSSEC", "Malware", "Ads", "Protocol",
        ]
        lines.append("| " + " | ".join(headers) + " |")

        # Separator row (right-align numeric columns)
        aligns = ["---:", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", ":---:", ":---:", ":---:", "---"]
        lines.append("| " + " | ".join(aligns) + " |")

        # Data rows
        for rank, s in enumerate(results, start=1):
            srv = s.server
            row = [
                str(rank),
                srv.get("name", "Unknown"),
                f"{s.score:.1f}",
                _fmt(s.avg_ms),
                _fmt(s.median_ms),
                _fmt(s.p95_ms),
                _fmt(s.min_ms),
                _fmt(s.max_ms),
                _fmt(s.jitter_ms),
                _pct(s.success_rate),
                _bool_str(s.dnssec_ok),
                _bool_str(s.malware_blocked),
                _bool_str(s.ads_blocked),
                srv.get("protocol", "udp"),
            ]
            lines.append("| " + " | ".join(row) + " |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by [DNSMark](https://natural.yt/dnsmark)*")
        lines.append("")

        return "\n".join(lines)
